variable "gcp_project_id" {
  description = "Google Cloud Project ID"
  type        = string
}

variable "gcp_region" {
  description = "The dynamic region chosen by the Carbon Scheduler"
  type        = string
}

variable "ssh_user" {
  description = "The SSH username"
  type        = string
  default     = "runner"
}

variable "ssh_pub_key" {
  description = "The public SSH key generated by GitHub Actions"
  type        = string
}