variable "gcp_project_id" {
  description = "Google Cloud Project ID"
  type        = string
}

variable "gcp_region" {
  description = "The dynamic region chosen by the Carbon Scheduler"
  type        = string
}

variable "ssh_user" {
  description = "The SSH username"
  type        = string
  default     = "runner"
}

variable "ssh_pub_key" {
  description = "The public SSH key generated by GitHub Actions"
  type        = string
}

variable "gcp_machine_type" {
  description = "Dynamic VM Type chosen by Python Profile"
  type        = string
}

variable "gcp_provisioning_model" {
  description = "SPOT or STANDARD"
  type        = string
}

variable "runner_name" {
  description = "Name and run_type label for this runner (e.g. green-thesis-runner, cost-runner, lat-e2-runner, lat-c2-runner)"
  type        = string
  default     = "green-thesis-runner"
}

variable "workload" {
  description = "The workload type passed from GitHub Actions (e.g. SHORT, MID, LONG)"
  type        = string
  default     = "short"
}